/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#2b5982",
        "on-secondary-fixed-variant": "#184a72",
        "surface": "#faf9fe",
        "on-tertiary-fixed-variant": "#593483",
        "on-primary-fixed-variant": "#4130ac",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eeedf3",
        "surface-container-high": "#e9e7ed",
        "outline-variant": "#c8c4d5",
        "primary": "#5749c2",
        "on-tertiary-container": "#fffbff",
        "on-secondary-fixed": "#001d34",
        "secondary-fixed-dim": "#9fcafa",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-dim": "#dad9df",
        "surface-container-low": "#f4f3f8",
        "tertiary-fixed-dim": "#dbb8ff",
        "surface-tint": "#5a4bc5",
        "primary-container": "#7063dd",
        "primary-fixed": "#e4dfff",
        "background": "#faf9fe",
        "on-error": "#ffffff",
        "on-primary-container": "#fffbff",
        "inverse-on-surface": "#f1f0f5",
        "surface-bright": "#faf9fe",
        "outline": "#787585",
        "tertiary-container": "#8963b5",
        "on-primary": "#ffffff",
        "secondary-container": "#a5d0ff",
        "surface-variant": "#e3e2e7",
        "secondary-fixed": "#cfe4ff",
        "inverse-primary": "#c6bfff",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c6bfff",
        "on-tertiary-fixed": "#2b0052",
        "on-background": "#1a1b1f",
        "secondary": "#35618b",
        "on-surface-variant": "#474553",
        "on-surface": "#1a1b1f",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#160066",
        "tertiary-fixed": "#efdbff",
        "inverse-surface": "#2f3034",
        "tertiary": "#704a9a",
        "surface-container-highest": "#e3e2e7",
        "on-secondary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
